version: "3"
services:
  dynamo:
    image: cnadiminti/dynamodb-local:latest
    ports:
      - 8000:8000
  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
    volumes:
      - /data
    environment:
      MINIO_ACCESS_KEY: A1B2C3D4E5
      MINIO_SECRET_KEY: A1B2C3D4E5
    command: server /data