version: "3"
services:
  s3:
    image: minio/minio:latest 
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: A1B2C3D4E5
      MINIO_SECRET_KEY: A1B2C3D4E5
    command: server /data
  dynamo:
    image: cnadiminti/dynamodb-local:latest
    ports:
      - 8000:8000